# Generated by Django 3.2.25 on 2024-04-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_gifts_occacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gifts',
            new_name='Gift',
        ),
        migrations.RenameModel(
            old_name='Occacion',
            new_name='Occasion',
        ),
        migrations.RenameField(
            model_name='gift',
            old_name='occacion',
            new_name='occasion',
        ),
    ]
